### ISSUE TITLE
Icons and headers

### ISSUE THREAD

**Issue by Rouche** [acoop133/GithubDarkTheme#3]
**Improvement to be done**

Hi, great theme BTW. I had trouble reading some of the elements.
Here are my suggestions, I made the icons a little bit clearer:
```
table.files td.icon {
    color: rgba(125,195,245,.9);
}
table.files td.icon .octicon-file-directory {
    color: rgba(125,195,255,.9);
}
```
Also some made panels headers grey, to differentiate them.
```
/* headers */
.table-list-header,
...
.merge-status-item {
    background: #454545 !important;
}
```
Give this:
![image](https://user-images.githubusercontent.com/1267438/55447407-9df1d000-5591-11e9-8264-9b96d1485bb9.png)

**Comment by acoop133** [comment]
Thanks for the feedback! I will implement this when I find some time :)

**Comment by acoop133** [comment]
https://github.com/acoop133/GithubDarkTheme/pull/4

**Comment by acoop133** [comment]
Update and Enjoy! :)
