### ISSUE TITLE
Theme not working in help.github.com

### ISSUE THREAD

**Issue by joulev** [acoop133/GithubDarkTheme#30]
The theme works very well with https://github.com/ but not https://help.github.com/en:

* It is not really a "dark theme" there:

  ![](https://i.imgur.com/YXzGcMH.png)

* It almost hides some contents:

  ![](https://i.imgur.com/7tsrQEe.png)

I use Google Chrome.

**Comment by acoop133** [comment]
I've made my best attempt at making it all dark, but some retard responsible for github help page think its funny to directly set style inside div with no identifier.

The page had like no effort put in either...

**Comment by acoop133** [comment]
Just looked through some pages, still some unthemed....
