### ISSUE TITLE
Labels have no background color

### ISSUE THREAD

**Issue by KrasnovPavel** [acoop133/GithubDarkTheme#34]
Labels have no background color
![image](https://user-images.githubusercontent.com/5003831/59511623-75565280-8ebf-11e9-89d1-d11cdc58155f.png)
Browser: Chrome.

**Comment by acoop133** [comment]
Thanks for reporting, I will take a look later today :)

**Comment by acoop133** [comment]
i noticed theres a white fadevon that panel.  I dont have that in my chromium browser. and definitely not consistent to the theme.

Are you using another theme with this theme?
What browser are you using?

**Comment by KrasnovPavel** [comment]
This white fade is cool :) You don't need to fix it. 

I don't use another theme on github. My browser is Google Chrome Version 74.0.3729.169 (Official Build) (64-bit) on Windows 10 version 1809.

**Comment by acoop133** [comment]
It has to be some sort of A/B testing with Github, because i dont have that `Show more` text either.
![image](https://user-images.githubusercontent.com/19627023/59547023-d61d7380-8f2f-11e9-8731-a6a34f5313c5.png)

**Comment by KrasnovPavel** [comment]
I think it is because i have a lot of text in that issue. You can try to add two or three paragraphs of text to see it.

**Comment by acoop133** [comment]
You're right.
![image](https://user-images.githubusercontent.com/19627023/59547080-bfc3e780-8f30-11e9-8a70-e06eb7009252.png)
