### ISSUE TITLE
Pop-up message on main page looks odd.

### ISSUE THREAD

**Issue by KrasnovPavel** [acoop133/GithubDarkTheme#39]
Great theme but still has something to fix.
Original
![image](https://user-images.githubusercontent.com/5003831/59549087-27922680-8f61-11e9-8c3f-6094d5dbee1f.png)
Dark theme
![image](https://user-images.githubusercontent.com/5003831/59549104-70e27600-8f61-11e9-9100-d692c4d64433.png)
1) Same color for private and public repos, but it is ok. 
2) Triangle still white.
3) No border and shades.
4) No border around "Private" label (on every screen, not only main page).

**Comment by KrasnovPavel** [comment]
By the way, there is some issues on issue preview.
![image](https://user-images.githubusercontent.com/5003831/59549293-126ac700-8f64-11e9-9877-a88ee74b7e9d.png)
This white line looks odd.

![image](https://user-images.githubusercontent.com/5003831/59549298-2a424b00-8f64-11e9-9388-2e1be446e21d.png)
![image](https://user-images.githubusercontent.com/5003831/59549303-3c23ee00-8f64-11e9-9afc-2b5c2b79e01a.png)
There is something wrong with bottom margin.

**Comment by acoop133** [comment]
I cant reproduce the last one. ive also tried removing the moto. 
![image](https://user-images.githubusercontent.com/19627023/59568792-d1fc6d80-9077-11e9-93ea-f5d34f207519.png)

**Comment by acoop133** [comment]
maybe my other css indirectly fixed it somehow

**Comment by KrasnovPavel** [comment]
Still there is an issue with padding in "Create Pull Request" window.
![image](https://user-images.githubusercontent.com/5003831/59583087-e75ab180-90e2-11e9-8987-fc5763b324f2.png)
