### ISSUE TITLE
Background color for buttons

### ISSUE THREAD

**Issue by KrasnovPavel** [acoop133/GithubDarkTheme#44]
Hi! 
You should consider to change buttons background color or add border around them. They have the same color as some panels.
![image](https://user-images.githubusercontent.com/5003831/59742250-e60dbe00-9275-11e9-843e-b061bae736e1.png)
![image](https://user-images.githubusercontent.com/5003831/59742572-b612ea80-9276-11e9-95a8-5bd6ec092cbb.png)

On screenshots I can find buttons only because I know that they should be there.

**Comment by acoop133** [comment]
got work in the morning, so i shall sleep and finish the last one after work if i have time (write, preview)  :^)

I should probably also make the hover colour of gray buttons to be lighter instead of darker. what do you think?
