### ISSUE TITLE
screenshot of GithubDarkTheme(); in Stylish very strange

### ISSUE THREAD

**Issue by tessus** [acoop133/GithubDarkTheme#69]
**Describe the bug**
When I open the stylish add-on, I can see the theme under the list of installed styles.
However, the screenshot only says `GitHub`. see screenshot below

**Expected behavior**
I would have expected a nice screenshot of the theme instead.

**Screenshots**
<img width="258" alt="image" src="https://user-images.githubusercontent.com/223439/63207890-de16a280-c09b-11e9-89a1-82373f85c204.png">

**Desktop (please complete the following information):**
macOS 10.14.6
Firefox 68.0.2

**Smartphone (please complete the following information):**
I don't use a smartphone to access github.

---

This is certainly not an important issue, but I wanted to mention it. Maybe something went wrong with the latest update and nobody noticed it. Anyway, I love the theme.
Keep up the great work! Cheers.

**Comment by acoop133** [comment]
Hi @tessus, that image was the first image ever uploaded for the theme and was changed soon after. 
I cant really do anything from here I'm afraid.

on the bright side, its not always showing that image.
![image](https://user-images.githubusercontent.com/19627023/63211152-67a19100-c0eb-11e9-980b-9fc2e8dd5f81.png)

Thanks for raising this problem and im glad you like the theme :)

Im also working on a chrome extension atm to deploy this theme, auto updates and fix areas that needs html injection that stylus doesn't provide :)
https://github.com/acoop133/GithubDarkTheme/tree/Chrome-Extension-Master 

its close to completion but im a bit distracted by other things atm :D.

**Comment by acoop133** [comment]
See gif :)

![h0wP45Xiib](https://user-images.githubusercontent.com/19627023/63211242-a126cc00-c0ec-11e9-99cf-745e34eb9469.gif)

**Comment by tessus** [comment]
Thank you very much for your reply. The Chrome extension won't help for Firefox, will it? I guess that is what the gif is showing.
Anyway, the screenshot is not important, it just stood out.

Hmm, I guess whoever hosts that screenshot has a caching issue. If the image was replaced, why is it still showing up? Especially since I installed Stylish and the theme only today (for the first time ever)? This makes no sense. Anyway, it's not important, just something I don't understand....

Thanks again.

**Comment by acoop133** [comment]
Firefox extension will follow.  they're using same api so it wont be hard.

**Comment by tessus** [comment]
So will this extension be for your theme alone or will it "replace" Stylish?

**Comment by acoop133** [comment]
my theme alone. my theme's css uri is hardcoded, it gets the css file via github api, which means i wont need to host anything. :)

though anyone can change the uri and compile their own version of the extension if they wanted to.

It makes more sense to extend the existing stylish extension but knowing there are many smart people out there that could have added an auto updater a long time ago and it doesnt exist, Its safe to assume its not easy and i just dont have time for that :P.

Plus coding an extension from scratch is beneficial for portfolio :P

**Comment by acoop133** [comment]
https://github.com/acoop133/GithubDarkTheme/blob/7257c531c78f71c4cd1552097eacfe1a1315e360/Extensions/Chrome/src/popup/Update.tsx#L109
