### ISSUE TITLE
certain timeline items are still white instead of gray

### ISSUE THREAD

**Issue by tessus** [acoop133/GithubDarkTheme#76]
**Describe the bug**
There are a few items in the timeline which are still white, including the line connecting them.

**Expected behavior**
The items and the lines should be gray.

**Screenshots**
<img width="60" alt="image" src="https://user-images.githubusercontent.com/223439/64093663-49f93c00-cd27-11e9-90fb-ae2dbd5c4071.png">
see `https://github.com/laurent22/joplin/pull/1804`
<img width="147" alt="image" src="https://user-images.githubusercontent.com/223439/64093719-7b720780-cd27-11e9-8a97-96615e0953e8.png">
see `https://github.com/acoop133/GithubDarkTheme/issues/68`

**Desktop (please complete the following information):**
Firefox 68.0.2 on macOS 10.14.6

**Smartphone (please complete the following information):**
Not using github on amartphone

**Comment by acoop133** [comment]
Thanks for reporting, i will release [1.11](https://github.com/acoop133/GithubDarkTheme/milestone/6) tonight. :)

**Comment by tessus** [comment]
awesome. thx.
