### ISSUE TITLE
warning message not readable

### ISSUE THREAD

**Issue by tessus** [acoop133/GithubDarkTheme#81]
**Describe the bug**
When you access a repository and a user, whom you blocked, has contributed to it before, you get a message that states exactly that fact. Unfortunately you can't read it.

**Expected behavior**
The text should be readable.

**Screenshots**
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/223439/64480347-d7a7b200-d193-11e9-94ed-5688566824f6.png">

The text in there reads "A user you’ve blocked has previously contributed to this repository.", but you can only see it, if you select it:

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/223439/64480353-f443ea00-d193-11e9-9511-c0fc8bde3f78.png">

**Desktop (please complete the following information):**
Firefox 69 on macOS 10.14.6

**Smartphone (please complete the following information):**
Not using github on amartphone

**Comment by acoop133** [comment]
hows this? 
![image](https://user-images.githubusercontent.com/19627023/64480587-4996f000-d1c2-11e9-8c50-f37c2400531b.png)

**Comment by acoop133** [comment]
![image](https://user-images.githubusercontent.com/19627023/64480598-8fec4f00-d1c2-11e9-8f87-9124b0ec20d8.png)
Or a bit less disgusting yellow :D

**Comment by tessus** [comment]
Yep, whatever you like. It could also be a faint red (not a screaming red). I don't really care about the color as long as one can read the text. You are a designer, I trust your decisions.
e.g. you could even leave the original color, if the text is changed to gray or black.
Whatever fits best to the rest of your theme.

**Comment by acoop133** [comment]
![image](https://user-images.githubusercontent.com/19627023/64490401-611eb900-d254-11e9-8012-bcf36c9772aa.png)

**Comment by tessus** [comment]
Great, thanks.
